server.port=8080
spring.datasource.url=jdbc:h2:mem:plantcare
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

enable.swagger.plugin=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

spring.security.user.name=kavi
spring.security.user.password=$2a$10$49lmuXCJnQkXYNf/ZH2yquLPH8pRYDrY6BnotcSeC1rSuK6N8YFL.
